version: '3'
services:
  app:
    build: .
    container_name: app
    command: /bin/bash -c 'mix ecto.migrate && mix run --no-halt'
    ports:
      - 4000:4000
    depends_on:
      - db
      - rabbitmq
    environment: 
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_HOST: rabbitmq
  rabbitmq: 
    image: rabbitmq:3-management
    container_name: rabbitmq-container
    ports: 
      - 5673:5672
      - 15673:15672
    volumes: 
      - etc-rabbit-volume:/var/etc/rabbitmq/
      - data-rabbit-volume:/var/lib/rabbitmq/
      - logs-rabbit-volume:/var/log/rabbitmq/
    environment: 
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
  db:
    image: postgres
    ports: 
      - "5433:5432"
    container_name: postgres
    environment: 
      POSTGRES_DB: "User"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - data-volume:/var/lib/db
volumes:
  data-volume:
  etc-rabbit-volume:
  data-rabbit-volume:
  logs-rabbit-volume: