version: '3.7'

services:
  user:
    restart: always
    image: kedith/user-conference:latest
    container_name: user
    ports:
      - 4005:4000
    depends_on:
      - userDb
    links:
      - userDb
  userDb:
    restart: always
    image: postgres:11.0
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: "User"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - data-volume:/var/lib/userDb
volumes:
  data-volume: