version: '3'
services:
  app:
    build: .
    command: /bin/bash -c 'mix ecto.migrate && mix run --no-halt'
    ports:
      - "4000:4000"
    depends_on:
      - db
  db:
    image: postgres
    environment: 
      POSTGRES_DB: "User"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"